/**
 * Maison Intelligence Layer — Discovery Intelligence
 *
 * Derives discovery collection character from MKC data via frequency aggregation
 * and representative selection over the products generated by each CollectionSpec.
 * Results reflect dominant tendencies — not absolute rules about every fragrance.
 *
 * Responsibilities:
 *   - Sole aggregation layer for discovery collection dimensions (EP23-P1, Refinement 2).
 *   - Sole selection layer for representative fragrances (EP23-P2, Refinement 3).
 *   - Distinct from app/lib/mkc/collectionIntelligence.ts (EP22-P4), which describes
 *     Skye / Rose / Elite identity. This module describes generated discovery
 *     collections — a different slice of the catalogue.
 *
 * Performance: All collections precomputed at module initialisation.
 * Page components resolve from precomputed Maps — no per-render catalogue scans.
 *
 * EP23-P2 representative selection. Future evolution points (Refinement 7):
 *   - Relationship Graph weighting
 *   - Discovery pathway emphasis
 *   - Seasonal emphasis
 *   - Native knowledge weighting
 *   - Wardrobe relevance
 *
 * EP23-P1 dimension extension points:
 *   - Dominant scent character
 *   - Seasonal pathways
 *   - Collection comparisons
 *   - Guided discovery journeys
 */

import type { FragranceKnowledge } from "../mkc/types";
import { getCollection, COLLECTION_SPECS } from "./collectionEngine";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface CollectionDimensions {
  /** Top fragrance families by frequency across the generated collection. */
  topFamilies:  string[];
  /** Top occasions by frequency across the generated collection. */
  topOccasions: string[];
  /** Top seasons by frequency across the generated collection. */
  topSeasons:   string[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function countFrequency(items: string[]): Map<string, number> {
  const freq = new Map<string, number>();
  for (const item of items) {
    freq.set(item, (freq.get(item) ?? 0) + 1);
  }
  return freq;
}

function topByFrequency(freq: Map<string, number>, limit: number): string[] {
  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([item]) => item);
}

// ── Aggregation ───────────────────────────────────────────────────────────────

function computeDimensions(id: string): CollectionDimensions {
  const records = getCollection(id);
  return {
    topFamilies:  topByFrequency(countFrequency(records.flatMap((r) => r.family)),   4),
    topOccasions: topByFrequency(countFrequency(records.flatMap((r) => r.occasions)), 4),
    // Uses r.seasons (plural discovery array) — richer than singular r.season.
    // A fragrance surfaces in frequency for every season it suits, not just its primary one.
    topSeasons:   topByFrequency(countFrequency(records.flatMap((r) => r.seasons)),   3),
  };
}

// ── Precomputed dimensions map ────────────────────────────────────────────────
// Computed once at module initialisation for all collection specs.
// Keyed by CollectionSpec.id.

const DIMENSIONS_MAP = new Map<string, CollectionDimensions>(
  COLLECTION_SPECS.map((spec) => [spec.id, computeDimensions(spec.id)])
);

export function getCollectionDimensions(id: string): CollectionDimensions | undefined {
  return DIMENSIONS_MAP.get(id);
}

// ── Representative fragrances ─────────────────────────────────────────────────
// Selects up to 2 fragrances that illustrate the character of a collection.
// These are educational examples — not recommendations, rankings, or top picks.
//
// Selection strategy (Refinement 4):
//   1. Prefer native records (catalogVersion set) — richer authored editorial data.
//      Fall back to the full pool when no native records exist in the collection.
//   2. Highest collection-fit: getCollection() is already sorted by boost score;
//      the pool order is authoritative — most representative records come first.
//   3. Editorial diversity: prefer different primary families between the two
//      selections so customers see different expressions of the collection.
//   4. Graceful fallback: if the diversity pass yields fewer than 2, fill
//      remaining slots from the pool without the family constraint.

function selectRepresentatives(
  id:    string,
  count: number = 2
): FragranceKnowledge[] {
  const records = getCollection(id);

  // Prefer native records — fall back to full pool if none present.
  const natives = records.filter((r) => r.catalogVersion !== undefined);
  const pool    = natives.length > 0 ? natives : records;

  // Diversity pass: build up to `count` with different primary families.
  const selected: FragranceKnowledge[] = [];
  const usedFamilies = new Set<string>();

  for (const record of pool) {
    if (selected.length >= count) break;
    const primaryFamily = record.family[0] ?? "";
    if (primaryFamily && usedFamilies.has(primaryFamily) && selected.length > 0) continue;
    if (primaryFamily) usedFamilies.add(primaryFamily);
    selected.push(record);
  }

  // Fill pass: add remaining slots regardless of family.
  if (selected.length < count) {
    for (const record of pool) {
      if (selected.length >= count) break;
      if (!selected.includes(record)) selected.push(record);
    }
  }

  return selected;
}

// ── Precomputed representatives map ──────────────────────────────────────────

const REPRESENTATIVES_MAP = new Map<string, FragranceKnowledge[]>(
  COLLECTION_SPECS.map((spec) => [spec.id, selectRepresentatives(spec.id)])
);

export function getRepresentativeFragrances(id: string): FragranceKnowledge[] {
  return REPRESENTATIVES_MAP.get(id) ?? [];
}
