/**
 * Maison Intelligence Layer — Discovery Intelligence
 *
 * Derives discovery collection character from MKC data via frequency aggregation
 * over the products generated by each CollectionSpec. Results reflect dominant
 * tendencies across a curated collection — not absolute rules about every fragrance.
 *
 * Responsibilities:
 *   - Sole aggregation layer for discovery collection dimensions (EP23-P1, Refinement 2).
 *   - Distinct from app/lib/mkc/collectionIntelligence.ts (EP22-P4), which describes
 *     Skye / Rose / Elite identity. This module describes generated discovery
 *     collections — a different slice of the catalogue (Refinement 3).
 *
 * Performance: All collections precomputed at module initialisation (Refinement 7).
 * Page components call getCollectionDimensions() which resolves from a precomputed Map.
 * No per-render aggregation takes place in page components (Refinement 2).
 *
 * EP23-P1 foundation. Future extension points (Refinement 6):
 *   - Dominant scent character
 *   - Representative native fragrances
 *   - Seasonal pathways
 *   - Collection comparisons
 *   - Guided discovery journeys
 */

import { getCollection, COLLECTION_SPECS } from "./collectionEngine";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface CollectionDimensions {
  /** Top fragrance families by frequency across the generated collection. */
  topFamilies:  string[];
  /** Top occasions by frequency across the generated collection. */
  topOccasions: string[];
  /** Top seasons by frequency across the generated collection. */
  topSeasons:   string[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function countFrequency(items: string[]): Map<string, number> {
  const freq = new Map<string, number>();
  for (const item of items) {
    freq.set(item, (freq.get(item) ?? 0) + 1);
  }
  return freq;
}

function topByFrequency(freq: Map<string, number>, limit: number): string[] {
  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([item]) => item);
}

// ── Aggregation ───────────────────────────────────────────────────────────────

function computeDimensions(id: string): CollectionDimensions {
  const records = getCollection(id);
  return {
    topFamilies:  topByFrequency(countFrequency(records.flatMap((r) => r.family)),   4),
    topOccasions: topByFrequency(countFrequency(records.flatMap((r) => r.occasions)), 4),
    // Uses r.seasons (plural discovery array) — richer than singular r.season.
    // A fragrance surfaces in frequency for every season it suits, not just its primary one.
    topSeasons:   topByFrequency(countFrequency(records.flatMap((r) => r.seasons)),   3),
  };
}

// ── Precomputed map ───────────────────────────────────────────────────────────
// Computed once at module initialisation for all collection specs.
// Keyed by CollectionSpec.id.

const DIMENSIONS_MAP = new Map<string, CollectionDimensions>(
  COLLECTION_SPECS.map((spec) => [spec.id, computeDimensions(spec.id)])
);

export function getCollectionDimensions(id: string): CollectionDimensions | undefined {
  return DIMENSIONS_MAP.get(id);
}
