/**
 * Maison Intelligence Layer — Discovery Intelligence
 *
 * Derives discovery collection character from MKC data via frequency aggregation
 * and representative selection over the products generated by each CollectionSpec.
 * Results reflect dominant tendencies — not absolute rules about every fragrance.
 *
 * Responsibilities:
 *   - Sole aggregation layer for discovery collection dimensions (EP23-P1, Refinement 2).
 *   - Sole selection layer for representative fragrances (EP23-P2, Refinement 3).
 *   - Distinct from app/lib/mkc/collectionIntelligence.ts (EP22-P4), which describes
 *     Skye / Rose / Elite identity. This module describes generated discovery
 *     collections — a different slice of the catalogue.
 *
 * Performance: All collections precomputed at module initialisation.
 * Page components resolve from precomputed Maps — no per-render catalogue scans.
 *
 * EP23-P3 guided discovery pathways — graph-driven exploration from representative
 * fragrances via the Relationship Graph (Refinement 2: graph.ts is the traversal API).
 * Future evolution points (Refinement 8):
 *   - Native knowledge weighting  ← EP26-P1: discoveryReadiness applied to representative selection
 *   - Seasonal context
 *   - Current collection context
 *   - Wardrobe awareness
 *   - Discovery progression
 *
 * EP23-P1 dimension extension points:
 *   - Dominant scent character
 *   - Seasonal pathways
 *   - Collection comparisons
 */

import type { FragranceKnowledge } from "../mkc/types";
import { getCollection, COLLECTION_SPECS } from "./collectionEngine";
import { buildIndex, getRelationshipSummary } from "../mkc/graph";
import { mkcCatalogue } from "../mkc/catalogue";
import { getKnowledgeQuality } from "../mkc/knowledgeQuality";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface CollectionDimensions {
  /** Top fragrance families by frequency across the generated collection. */
  topFamilies:  string[];
  /** Top occasions by frequency across the generated collection. */
  topOccasions: string[];
  /** Top seasons by frequency across the generated collection. */
  topSeasons:   string[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function countFrequency(items: string[]): Map<string, number> {
  const freq = new Map<string, number>();
  for (const item of items) {
    freq.set(item, (freq.get(item) ?? 0) + 1);
  }
  return freq;
}

function topByFrequency(freq: Map<string, number>, limit: number): string[] {
  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, limit)
    .map(([item]) => item);
}

// ── Aggregation ───────────────────────────────────────────────────────────────

function computeDimensions(id: string): CollectionDimensions {
  const records = getCollection(id);
  return {
    topFamilies:  topByFrequency(countFrequency(records.flatMap((r) => r.family)),   4),
    topOccasions: topByFrequency(countFrequency(records.flatMap((r) => r.occasions)), 4),
    // Uses r.seasons (plural discovery array) — richer than singular r.season.
    // A fragrance surfaces in frequency for every season it suits, not just its primary one.
    topSeasons:   topByFrequency(countFrequency(records.flatMap((r) => r.seasons)),   3),
  };
}

// ── Precomputed dimensions map ────────────────────────────────────────────────
// Computed once at module initialisation for all collection specs.
// Keyed by CollectionSpec.id.

const DIMENSIONS_MAP = new Map<string, CollectionDimensions>(
  COLLECTION_SPECS.map((spec) => [spec.id, computeDimensions(spec.id)])
);

export function getCollectionDimensions(id: string): CollectionDimensions | undefined {
  return DIMENSIONS_MAP.get(id);
}

// ── Representative fragrances ─────────────────────────────────────────────────
// Selects up to 2 fragrances that illustrate the character of a collection.
// These are educational examples — not recommendations, rankings, or top picks.
//
// Selection strategy (Refinement 4, updated EP26-P1):
//   1. Prefer native records (catalogVersion set) — richer authored editorial data.
//      Fall back to the full pool when no native records exist in the collection.
//   2. Quality-aware ordering (EP26-P1): within the pool, sort by discoveryReadiness
//      DESC (Knowledge Quality), then popularity DESC. Records that have been more
//      fully authored for discovery surfaces rank ahead of adapter-only records.
//      No record is excluded — sort order shifts, not the candidate set.
//   3. Editorial diversity: prefer different primary families between the two
//      selections so customers see different expressions of the collection.
//   4. Graceful fallback: if the diversity pass yields fewer than 2, fill
//      remaining slots from the pool without the family constraint.

function selectRepresentatives(
  id:    string,
  count: number = 2
): FragranceKnowledge[] {
  const records = getCollection(id);

  // Prefer native records — fall back to full pool if none present.
  const natives = records.filter((r) => r.catalogVersion !== undefined);
  const pool    = natives.length > 0 ? natives : records;

  // Quality-aware sort (EP26-P1): discoveryReadiness DESC, then popularity DESC.
  // pool is already collection-relevant (boost-filtered by getCollection).
  // Within that set, Knowledge Quality determines editorial surfacing priority.
  const sortedPool = [...pool].sort((a, b) => {
    const drA = getKnowledgeQuality(a.slug)?.discoveryReadiness ?? 0;
    const drB = getKnowledgeQuality(b.slug)?.discoveryReadiness ?? 0;
    if (drB !== drA) return drB - drA;
    return b.popularity - a.popularity;
  });

  // Diversity pass: build up to `count` with different primary families.
  const selected: FragranceKnowledge[] = [];
  const usedFamilies = new Set<string>();

  for (const record of sortedPool) {
    if (selected.length >= count) break;
    const primaryFamily = record.family[0] ?? "";
    if (primaryFamily && usedFamilies.has(primaryFamily) && selected.length > 0) continue;
    if (primaryFamily) usedFamilies.add(primaryFamily);
    selected.push(record);
  }

  // Fill pass: add remaining slots regardless of family.
  if (selected.length < count) {
    for (const record of sortedPool) {
      if (selected.length >= count) break;
      if (!selected.includes(record)) selected.push(record);
    }
  }

  return selected;
}

// ── Precomputed representatives map ──────────────────────────────────────────

const REPRESENTATIVES_MAP = new Map<string, FragranceKnowledge[]>(
  COLLECTION_SPECS.map((spec) => [spec.id, selectRepresentatives(spec.id)])
);

export function getRepresentativeFragrances(id: string): FragranceKnowledge[] {
  return REPRESENTATIVES_MAP.get(id) ?? [];
}

// ── Guided discovery pathways ─────────────────────────────────────────────────
// Maps representative fragrances to closely related fragrances via the Relationship
// Graph. Answers: "If this example interested you, here are closely related places
// to continue exploring." (EP23-P3, Refinement 1)
//
// All relationship traversal goes through getRelationshipSummary() — graph.ts
// remains the single traversal API (Refinement 2).
//
// Pathway priority (Refinement 4):
//   alternatives    → "A different expression of this style"
//   evolutions      → "A more intense interpretation"
//   wardrobePartners → "Often worn alongside"
//   evolutionOf     → "The origin of this fragrance line"
//
// Graceful degradation: representatives without authored graph relationships
// contribute nothing. If no representative has relationships, pathways is []
// and no section renders (Refinement 6).
//
// Duplicate prevention: representative slugs are excluded from pathway results;
// pathway targets are deduplicated across representatives (Refinement 7).
//
// Future evolution (Refinement 8):
//   - Native knowledge weighting
//   - Seasonal context
//   - Current collection context
//   - Wardrobe awareness
//   - Discovery progression

// Graph index built once at module initialisation — O(1) slug lookups thereafter.
const graphIndex = buildIndex(mkcCatalogue);

/** Explicit relationship category — consumed by Journey Intelligence for topic adaptation. */
export type PathwayType =
  | "alternative"      // comparable fragrance via a different route
  | "evolution"        // more intense descendant of this line
  | "wardrobe-partner" // recommended to own alongside
  | "origin";          // ancestor in this fragrance line

export interface DiscoveryPathway {
  /** The connected fragrance to explore. */
  fragrance: FragranceKnowledge;
  /** Educational label describing the relationship. Never promotional. */
  label:     string;
  /** Explicit relationship category for Journey Intelligence. Not rendered. */
  type:      PathwayType;
}

function computePathways(id: string): DiscoveryPathway[] {
  const reps                = REPRESENTATIVES_MAP.get(id) ?? [];
  const representativeSlugs = new Set(reps.map((r) => r.slug));
  const pathways:  DiscoveryPathway[] = [];
  const seenSlugs: Set<string>        = new Set();

  for (const rep of reps) {
    if (pathways.length >= 2) break;

    const summary = getRelationshipSummary(rep, graphIndex);
    if (!summary.hasRelationships) continue;

    // Ordered candidates — alternatives first, then evolutions, wardrobe partners,
    // then the ancestor. This priority produces the most exploratory journey.
    const candidates: Array<{ fragrance: FragranceKnowledge; label: string; type: PathwayType }> = [
      ...summary.alternatives.map(    (f) => ({ fragrance: f, label: "A different expression of this style",  type: "alternative"      as PathwayType })),
      ...summary.evolutions.map(      (f) => ({ fragrance: f, label: "A more intense interpretation",          type: "evolution"        as PathwayType })),
      ...summary.wardrobePartners.map((f) => ({ fragrance: f, label: "Often worn alongside",                   type: "wardrobe-partner" as PathwayType })),
      ...(summary.evolutionOf
        ? [{ fragrance: summary.evolutionOf, label: "The origin of this fragrance line", type: "origin" as PathwayType }]
        : []),
    ];

    for (const { fragrance, label, type } of candidates) {
      if (pathways.length >= 2) break;
      if (representativeSlugs.has(fragrance.slug)) continue; // already shown above
      if (seenSlugs.has(fragrance.slug)) continue;            // dedup across reps
      seenSlugs.add(fragrance.slug);
      pathways.push({ fragrance, label, type });
    }
  }

  return pathways;
}

// ── Precomputed pathways map ──────────────────────────────────────────────────
// PATHWAYS_MAP depends on REPRESENTATIVES_MAP, which is initialised above.
// Module evaluation order (top-to-bottom) guarantees REPRESENTATIVES_MAP is
// populated before this line executes.

const PATHWAYS_MAP = new Map<string, DiscoveryPathway[]>(
  COLLECTION_SPECS.map((spec) => [spec.id, computePathways(spec.id)])
);

export function getDiscoveryPathways(id: string): DiscoveryPathway[] {
  return PATHWAYS_MAP.get(id) ?? [];
}

// ── Journey topics ────────────────────────────────────────────────────────────
// Derives educational intent from collection character.
// Topics express WHAT a customer would benefit from learning — not which articles.
// Academy resolves topics to articles via resolveJourneyArticles() (journeyResolver.ts).
//
// Ownership:
//   Discovery Intelligence (this module) → derives topics from collection character
//   Academy resolver (journeyResolver.ts) → maps topics to articles
//
// EP24-P2: topic derivation is context-aware — three signal layers:
//   1. Collection dimensions (aggregate frequency — broad signal)
//   2. Representative families (specific native records — more precise signal)
//   3. Pathway relationship types (what exploration is already on the page)
//
// Only standard (non-editorial) collections receive journey topics.
// Editorial collections manage their own article sections via spec.editorial.articleSlugs.
//
// JOURNEY_TOPICS_MAP depends on DIMENSIONS_MAP, REPRESENTATIVES_MAP, and PATHWAYS_MAP —
// all initialised above. Module evaluation order (top-to-bottom) guarantees safety.

/** Educational topics derived from collection character. One topic per educational intent. */
export type JourneyTopic =
  | "fragrance-families"   // collection has notable family diversity
  | "seasonal-fragrance"   // collection has a strong specific season signal
  | "signature-scent"      // collection suits formal or signature occasions
  | "fragrance-wearing"    // general wearing guidance (fallback)
  | "note-pyramid"         // collection has depth/complexity (Oud, Amber, Spicy, Woody)
  | "fragrance-layering";  // wardrobe partner pathways present — layering is relevant

const DEEP_FAMILIES  = new Set(["Oud", "Amber", "Spicy", "Woody", "Oriental"]);
const FRESH_FAMILIES = new Set(["Fresh", "Citrus", "Aquatic", "Aromatic"]);
const EVENING_OCCS   = new Set(["Date Night", "Wedding", "Evening"]);

function computeJourneyTopics(id: string): JourneyTopic[] {
  const spec = COLLECTION_SPECS.find((s) => s.id === id);
  // Editorial collections manage their own article selection — skip.
  if (!spec || spec.editorial) return [];

  const dims  = DIMENSIONS_MAP.get(id);
  const reps  = REPRESENTATIVES_MAP.get(id) ?? [];
  const paths = PATHWAYS_MAP.get(id) ?? [];
  if (!dims) return [];

  const { topFamilies, topOccasions, topSeasons } = dims;
  const topics: JourneyTopic[] = [];

  // ── Layer 1: Collection dimension signals ─────────────────────────────────
  // Aggregate frequency over the full collection — broad directional signal.

  // Specific season dominant (topSeasons[0] is the most frequent — "All Season" excluded).
  if (topSeasons.length > 0 && topSeasons[0] !== "All Season")
    topics.push("seasonal-fragrance");

  // Deep/complex families: depth of composition is a notable learning signal.
  if (topFamilies.some((f) => DEEP_FAMILIES.has(f)))
    topics.push("note-pyramid");

  // Evening/signature occasions: identity and signature are relevant concepts.
  if (topOccasions.some((o) => EVENING_OCCS.has(o)))
    topics.push("signature-scent");

  // Fresh/aromatic families: family diversity is an educational entry point.
  if (topFamilies.some((f) => FRESH_FAMILIES.has(f)))
    topics.push("fragrance-families");

  // ── Layer 2: Representative family reinforcement ──────────────────────────
  // Representatives are the most specific, native-weighted records in the
  // collection. Their families surface signals the aggregate threshold may miss.
  if (!topics.includes("note-pyramid")) {
    const repFamilies = reps.flatMap((r) => r.family);
    if (repFamilies.some((f) => DEEP_FAMILIES.has(f)))
      topics.push("note-pyramid");
  }

  // ── Layer 3: Pathway relationship type adaptation ─────────────────────────
  // The relationship types shown on the page inform what is educationally adjacent.
  // Evolution/origin pathways → note pyramid (why fragrances intensify across a line).
  // Wardrobe partner pathways → layering (how fragrances complement one another).
  const pathwayTypes = new Set(paths.map((p) => p.type));

  if (!topics.includes("note-pyramid") &&
      (pathwayTypes.has("evolution") || pathwayTypes.has("origin")))
    topics.push("note-pyramid");

  if (pathwayTypes.has("wardrobe-partner"))
    topics.push("fragrance-layering");

  // ── Fallback ──────────────────────────────────────────────────────────────
  if (topics.length === 0)
    topics.push("fragrance-wearing");

  return topics;
}

// ── Precomputed journey topics map ────────────────────────────────────────────

const JOURNEY_TOPICS_MAP = new Map<string, JourneyTopic[]>(
  COLLECTION_SPECS.map((spec) => [spec.id, computeJourneyTopics(spec.id)])
);

export function getJourneyTopics(id: string): JourneyTopic[] {
  return JOURNEY_TOPICS_MAP.get(id) ?? [];
}

// ── Collection profile ────────────────────────────────────────────────────────
// A single public representation of the understood character of a collection.
// Consumed by Discovery Graph for connection scoring — the graph should never
// reconstruct individual intelligence independently (EP24-P3, Refinement 1).
//
// Contains all three layers of collection understanding:
//   - dimensions      (aggregate frequency — EP23-P1)
//   - representatives (native-weighted examples — EP23-P2)
//   - topics          (adaptive educational intent — EP24-P1/P2)
//
// As Discovery Intelligence evolves, the profile absorbs new layers here.
// Discovery Graph consumers remain decoupled from internal implementation.
//
// PROFILE_MAP depends on DIMENSIONS_MAP, REPRESENTATIVES_MAP, and JOURNEY_TOPICS_MAP —
// all initialised above. Module evaluation order (top-to-bottom) guarantees safety.

export interface CollectionProfile {
  /** Dominant families, occasions, and seasons across the collection. */
  dimensions:      CollectionDimensions;
  /** Up to 2 native-preferred fragrances illustrating collection character. */
  representatives: FragranceKnowledge[];
  /** Adaptive educational topics derived from collection context. */
  topics:          JourneyTopic[];
}

const PROFILE_MAP = new Map<string, CollectionProfile>(
  COLLECTION_SPECS.map((spec) => [spec.id, {
    dimensions:      DIMENSIONS_MAP.get(spec.id) ??
                       { topFamilies: [], topOccasions: [], topSeasons: [] },
    representatives: REPRESENTATIVES_MAP.get(spec.id) ?? [],
    topics:          JOURNEY_TOPICS_MAP.get(spec.id) ?? [],
  }])
);

export function getCollectionProfile(id: string): CollectionProfile | undefined {
  return PROFILE_MAP.get(id);
}
