// @ts-check
/**
 * Less-Sweet Fallback Fix — Browser Rendering Verification
 *
 * MOCKED RENDERING VERIFICATION — NOT A LIVE MODEL TEST.
 *
 * Intercepts POST /api/concierge with a deterministic fixture generated by
 * the patched pipeline (gen-less-sweet-fixtures.ts). No LLM is called.
 *
 * Scenario E: No-match anchored refinement (sweetness=1 anchor, "less sweet" request)
 *
 *   E1. The explanation text appears in the chat bubble (anchor name present).
 *   E2. No [PRODUCT:slug] markers appear in the bubble.
 *   E3. No product card links appear in the panel (fragrances=[]).
 *   E4. The cardTarget default-fill path does not repopulate cards.
 *   E5. The follow-up suggestions contain a question or direction hint (not product cards).
 *
 * Run:
 *   npx playwright test --config scripts/pw-verify/playwright.less-sweet.config.ts
 */

const { test, expect } = require('@playwright/test');
const fs   = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '../results/concierge-less-sweet');
fs.mkdirSync(OUT, { recursive: true });

const FIXTURES_PATH = path.join(__dirname, '../fixtures/concierge-less-sweet.json');
const FIXTURES      = JSON.parse(fs.readFileSync(FIXTURES_PATH, 'utf8'));

const BASE = 'http://localhost:3104';

async function openAndSendMessage(page, fixtureResponse, messageText) {
  let interceptCount = 0;

  await page.route('**/api/concierge', async (route) => {
    if (route.request().method() !== 'POST') {
      await route.continue();
      return;
    }
    interceptCount++;
    await route.fulfill({
      status:      200,
      contentType: 'application/json',
      body:        JSON.stringify(fixtureResponse),
    });
  });

  await page.goto(BASE);

  const triggerBtn = page.getByRole('button', { name: 'Ask the Maison Concierge' });
  await expect(triggerBtn).toBeVisible({ timeout: 15_000 });
  await triggerBtn.click();

  const dialog = page.getByRole('dialog', { name: 'Maison Concierge' });
  await expect(dialog).toBeVisible({ timeout: 5_000 });

  const textarea = dialog.getByRole('textbox', { name: 'Message' });
  await textarea.fill(messageText);
  await dialog.getByRole('button', { name: 'Send' }).click();

  await page.waitForFunction(() => {
    const dots = document.querySelector('.animate-bounce');
    return !dots;
  }, null, { timeout: 10_000 });

  expect(interceptCount).toBeGreaterThanOrEqual(1);

  return dialog;
}

// ── Scenario E: No-match anchored refinement ──────────────────────────────────

test('E: no-match anchored — explanation text in bubble, zero product cards', async ({ page }) => {
  const fixture    = FIXTURES.scenarioE;
  const anchorName = fixture._meta.anchorName;

  const dialog = await openAndSendMessage(
    page,
    fixture,
    `like ${anchorName} but less sweet`,
  );

  const bubble = dialog.locator('.rounded-tl-sm').last();
  await expect(bubble).toBeVisible({ timeout: 5_000 });

  const bubbleText = await bubble.textContent();

  // E1: Explanation references the anchor name
  expect(bubbleText, 'E1: anchor name present in explanation').toContain(anchorName);

  // E2: No [PRODUCT:slug] marker leaked to UI
  expect(bubbleText, 'E2: no [PRODUCT: marker in bubble').not.toContain('[PRODUCT:');

  // E3: No orphaned **** (bold-wrap artefact)
  expect(bubbleText, 'E3: no orphaned **** in bubble').not.toContain('****');
});

test('E: no-match anchored — zero product card links in panel', async ({ page }) => {
  const fixture = FIXTURES.scenarioE;

  const dialog = await openAndSendMessage(
    page,
    fixture,
    `like ${fixture._meta.anchorName} but less sweet`,
  );

  // Wait for bubble to appear
  const bubble = dialog.locator('.rounded-tl-sm').last();
  await expect(bubble).toBeVisible({ timeout: 5_000 });

  // E4: No /product/ links rendered (zero fragrance cards)
  const productLinks = dialog.locator('a[href^="/product/"]');
  const count = await productLinks.count();
  expect(count, 'E4: zero product card links in panel for no-match response').toBe(0);
});

// ── Scenario F: Multi-turn anchor persistence ─────────────────────────────────
// Establishes an anchor via the no-match fixture, then sends a follow-up message
// and inspects the second API request body to verify the anchor slug is preserved
// in state.selectedSlug and state.profile is carried forward.
//
// NOTE: This test verifies that the CLIENT correctly applies sessionUpdates from
// the first response and carries state forward. It does NOT verify that the model
// will follow the no-match instructions — that limitation is documented.

test('F: multi-turn — anchor slug carried in second API request state', async ({ page }) => {
  const fixture    = FIXTURES.scenarioE;
  const anchorSlug = fixture._meta.anchorSlug;
  const anchorName = fixture._meta.anchorName;

  let callCount        = 0;
  let secondRequestBody = null;

  await page.route('**/api/concierge', async (route) => {
    if (route.request().method() !== 'POST') {
      await route.continue();
      return;
    }
    callCount++;
    if (callCount === 1) {
      // First call: return the no-match fixture (establishes anchor via sessionUpdates)
      await route.fulfill({
        status:      200,
        contentType: 'application/json',
        body:        JSON.stringify(fixture),
      });
    } else {
      // Second call: capture the request body before fulfilling
      try {
        secondRequestBody = JSON.parse(route.request().postData() || '{}');
      } catch (_) {}
      // Return a minimal valid response to let the second turn complete
      await route.fulfill({
        status:      200,
        contentType: 'application/json',
        body:        JSON.stringify({
          content:    'What kind of scent direction would you like to explore?',
          fragrances: [],
          articleSlugs: [],
          intent:     'general_discovery',
          sessionUpdates: { selectedSlug: anchorSlug },
        }),
      });
    }
  });

  await page.goto(BASE);

  const triggerBtn = page.getByRole('button', { name: 'Ask the Maison Concierge' });
  await expect(triggerBtn).toBeVisible({ timeout: 15_000 });
  await triggerBtn.click();

  const dialog = page.getByRole('dialog', { name: 'Maison Concierge' });
  await expect(dialog).toBeVisible({ timeout: 5_000 });

  const textarea = dialog.getByRole('textbox', { name: 'Message' });

  // Turn 1: send anchor + direction request, intercepted with no-match fixture
  await textarea.fill(`like ${anchorName} but less sweet`);
  await dialog.getByRole('button', { name: 'Send' }).click();

  // Wait for first response bubble
  const bubble1 = dialog.locator('.rounded-tl-sm').last();
  await expect(bubble1).toBeVisible({ timeout: 10_000 });

  // Turn 2: send a follow-up to trigger the second API call
  await textarea.fill('What about a different direction?');
  await dialog.getByRole('button', { name: 'Send' }).click();

  // Wait for second response bubble to appear
  await page.waitForFunction(() => {
    return document.querySelectorAll('.rounded-tl-sm').length >= 2;
  }, null, { timeout: 10_000 });

  // F1: second API call must have been made
  expect(callCount, 'F1: second API call must have been made').toBeGreaterThanOrEqual(2);

  // F2: second request body must include state.selectedSlug === anchorSlug
  expect(secondRequestBody, 'F2: second request body must be captured').not.toBeNull();
  expect(
    secondRequestBody?.state?.selectedSlug,
    `F2: state.selectedSlug in second request must equal anchor slug (${anchorSlug})`
  ).toBe(anchorSlug);

  // F3: second request must include at least one conversation turn (the first exchange)
  const turnCount = secondRequestBody?.state?.turns?.length ?? 0;
  expect(turnCount, 'F3: second request state must include prior turns').toBeGreaterThanOrEqual(1);
});

// ── Scenario G: Three-turn — active preferences and anchor both persist ────────
// Turn 1: guest establishes preferences (gender + family) via intercepted response
// Turn 2: guest requests less-sweet anchor → intercepted with no-match fixture that
//         carries both selectedSlug and the profile in sessionUpdates
// Turn 3: follow-up message → API request captured, anchor AND preferences verified
//
// This test verifies that the CLIENT correctly accumulates sessionUpdates across
// two turns. It does NOT verify live model behaviour.

test('G: three-turn — anchor slug and active preferences both persist into third request', async ({ page }) => {
  const fixture    = FIXTURES.scenarioE;
  const anchorSlug = fixture._meta.anchorSlug;
  const anchorName = fixture._meta.anchorName;

  // Profile established in turn 1 and carried through turn 2
  const PROFILE = {
    preferredGender:   { value: 'female', confidence: 'HIGH' },
    preferredFamilies: { value: ['Floral'], confidence: 'HIGH' },
  };

  let callCount          = 0;
  let thirdRequestBody   = null;

  await page.route('**/api/concierge', async (route) => {
    if (route.request().method() !== 'POST') {
      await route.continue();
      return;
    }
    callCount++;

    if (callCount === 1) {
      // Turn 1: guest says "I'm looking for something feminine and floral"
      // Return a response that establishes the profile in sessionUpdates
      await route.fulfill({
        status:      200,
        contentType: 'application/json',
        body:        JSON.stringify({
          content:      "I'll look for feminine floral options for you.",
          fragrances:   [],
          articleSlugs: [],
          intent:       'general_discovery',
          sessionUpdates: {
            selectedSlug: null,
            profile:      PROFILE,
          },
        }),
      });
    } else if (callCount === 2) {
      // Turn 2: guest requests less-sweet anchor — return no-match fixture
      // Explicitly carry the profile so we can verify it survives to turn 3
      await route.fulfill({
        status:      200,
        contentType: 'application/json',
        body:        JSON.stringify({
          ...fixture,
          sessionUpdates: {
            selectedSlug: anchorSlug,
            profile:      PROFILE,
          },
        }),
      });
    } else {
      // Turn 3: capture the request body; return a minimal valid response
      try {
        thirdRequestBody = JSON.parse(route.request().postData() || '{}');
      } catch (_) {}
      await route.fulfill({
        status:      200,
        contentType: 'application/json',
        body:        JSON.stringify({
          content:      'Happy to explore a different direction.',
          fragrances:   [],
          articleSlugs: [],
          intent:       'general_discovery',
          sessionUpdates: { selectedSlug: anchorSlug, profile: PROFILE },
        }),
      });
    }
  });

  await page.goto(BASE);

  const triggerBtn = page.getByRole('button', { name: 'Ask the Maison Concierge' });
  await expect(triggerBtn).toBeVisible({ timeout: 15_000 });
  await triggerBtn.click();

  const dialog = page.getByRole('dialog', { name: 'Maison Concierge' });
  await expect(dialog).toBeVisible({ timeout: 5_000 });

  const textarea = dialog.getByRole('textbox', { name: 'Message' });

  // Turn 1: establish preferences
  await textarea.fill("I'm looking for something feminine and floral");
  await dialog.getByRole('button', { name: 'Send' }).click();
  await expect(dialog.locator('.rounded-tl-sm').last()).toBeVisible({ timeout: 10_000 });

  // Turn 2: anchor + direction request
  await textarea.fill(`like ${anchorName} but less sweet`);
  await dialog.getByRole('button', { name: 'Send' }).click();
  await page.waitForFunction(() => {
    return document.querySelectorAll('.rounded-tl-sm').length >= 2;
  }, null, { timeout: 10_000 });

  // Turn 3: follow-up message
  await textarea.fill('What else could you suggest?');
  await dialog.getByRole('button', { name: 'Send' }).click();
  await page.waitForFunction(() => {
    return document.querySelectorAll('.rounded-tl-sm').length >= 3;
  }, null, { timeout: 10_000 });

  // G1: third API call must have been made
  expect(callCount, 'G1: third API call must have been made').toBeGreaterThanOrEqual(3);

  // G2: third request must carry state.selectedSlug === anchorSlug (anchor persists)
  expect(thirdRequestBody, 'G2: third request body must be captured').not.toBeNull();
  expect(
    thirdRequestBody?.state?.selectedSlug,
    `G2: state.selectedSlug in third request must equal anchor slug (${anchorSlug})`
  ).toBe(anchorSlug);

  // G3: third request must carry the profile preferences from turn 1 (gender + family)
  const profileInRequest = thirdRequestBody?.state?.profile;
  expect(profileInRequest, 'G3: state.profile must be present in third request').not.toBeNull();
  expect(
    profileInRequest?.preferredGender?.value,
    'G3: preferredGender must persist from turn 1 into third request'
  ).toBe('female');
  expect(
    profileInRequest?.preferredFamilies?.value,
    'G3: preferredFamilies must persist from turn 1 into third request'
  ).toEqual(expect.arrayContaining(['Floral']));

  // G4: at least 2 prior turns in state (turns 1 + 2 exchanges recorded)
  const turnCount = thirdRequestBody?.state?.turns?.length ?? 0;
  expect(turnCount, 'G4: third request state must include prior turns').toBeGreaterThanOrEqual(2);
});
