import type { AcademyCategory } from "./types";

export type AcademyDifficulty = "beginner" | "intermediate" | "advanced";

export interface ArticleRegistryEntry {
  slug: string;
  category: AcademyCategory;
  difficulty: AcademyDifficulty;
  topics: string[];
  families: string[];       // MKC family names this article covers; [] = universal (all families)
  notes: string[];          // Note layer types discussed; e.g. ["top", "heart", "base"]
  occasions: string[];      // Lowercase MKC occasion strings this article targets; [] = universal
  collections: string[];    // MKC collections; [] = all collections
  keywords: string[];
  educationTags: string[];
  seasonal: boolean;        // True when the article is specifically about seasonal fragrance selection
  universalRelevance: boolean;
  relevanceScore: number;   // Baseline priority 0–100; higher = recommended more broadly
}

export const ARTICLE_REGISTRY: ArticleRegistryEntry[] = [
  {
    slug: "the-note-pyramid-explained",
    category: "The Note Pyramid",
    difficulty: "beginner",
    topics: [
      "note pyramid",
      "top notes",
      "heart notes",
      "base notes",
      "fragrance composition",
      "dry-down",
    ],
    families: [],
    notes: ["top", "heart", "base"],
    occasions: [],
    collections: [],
    keywords: [
      "note pyramid",
      "top notes",
      "heart notes",
      "base notes",
      "dry-down",
      "fragrance structure",
      "composition",
    ],
    educationTags: ["fundamentals", "composition", "structure", "note-pyramid"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 95,
  },

  {
    slug: "guide-to-fragrance-families",
    category: "Fragrance Families",
    difficulty: "beginner",
    topics: [
      "fragrance families",
      "family guide",
      "scent discovery",
      "fragrance vocabulary",
      "floral",
      "fresh",
      "woody",
      "oriental",
      "fruity",
      "gourmand",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "fragrance families",
      "floral",
      "fresh",
      "woody",
      "oriental",
      "fruity",
      "gourmand",
      "family guide",
      "scent vocabulary",
    ],
    educationTags: ["fundamentals", "families", "discovery", "vocabulary"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 90,
  },

  {
    slug: "how-to-wear-fragrance",
    category: "Wear & Application",
    difficulty: "beginner",
    topics: [
      "application technique",
      "pulse points",
      "longevity",
      "projection",
      "spray technique",
      "fragrance application",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "pulse points",
      "application",
      "longevity",
      "spray technique",
      "wear",
      "fragrance technique",
    ],
    educationTags: ["application", "technique", "basics", "wearability"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 80,
  },

  {
    slug: "what-makes-a-signature-scent",
    category: "Fragrance Fundamentals",
    difficulty: "beginner",
    topics: [
      "signature scent",
      "personal style",
      "fragrance identity",
      "everyday wear",
      "office scent",
      "daily fragrance",
    ],
    families: [],
    notes: [],
    occasions: ["daily wear", "office"],
    collections: [],
    keywords: [
      "signature scent",
      "everyday fragrance",
      "personal style",
      "identity",
      "office",
      "daily wear",
    ],
    educationTags: ["signature", "everyday", "personal-style", "fundamentals", "office"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 75,
  },

  {
    slug: "choosing-your-season-scent",
    category: "Occasions & Style",
    difficulty: "beginner",
    topics: [
      "seasonal fragrance",
      "summer scent",
      "winter scent",
      "spring scent",
      "autumn scent",
      "weather",
      "temperature",
    ],
    families: ["Fresh", "Aquatic", "Citrus", "Floral", "White Floral", "Rose", "Woody", "Amber", "Oud", "Spicy"],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "seasonal",
      "summer",
      "winter",
      "spring",
      "autumn",
      "weather",
      "temperature",
      "season",
    ],
    educationTags: ["seasonal", "occasions", "weather", "temperature"],
    seasonal: true,
    universalRelevance: false,
    relevanceScore: 70,
  },

  {
    slug: "how-to-layer-fragrances",
    category: "Wear & Application",
    difficulty: "intermediate",
    topics: [
      "layering",
      "fragrance combination",
      "creative technique",
      "base fragrance",
      "complementary families",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "layering",
      "combining fragrances",
      "stacking",
      "technique",
      "composition",
      "fragrance layering",
    ],
    educationTags: ["layering", "technique", "advanced-application", "creative"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 65,
  },

  {
    slug: "fragrance-concentration-explained",
    category: "Fragrance Fundamentals",
    difficulty: "beginner",
    topics: [
      "concentration",
      "EDT",
      "EDP",
      "parfum",
      "extrait",
      "longevity",
      "oil percentage",
      "eau de toilette",
      "eau de parfum",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "EDT",
      "EDP",
      "parfum",
      "extrait",
      "concentration",
      "eau de toilette",
      "eau de parfum",
      "longevity",
      "how long fragrance lasts",
    ],
    educationTags: ["concentration", "fundamentals", "longevity", "buying-guide"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 85,
  },

  {
    slug: "projection-and-sillage",
    category: "Fragrance Fundamentals",
    difficulty: "beginner",
    topics: [
      "projection",
      "sillage",
      "trail",
      "beast mode",
      "skin scent",
      "fragrance radius",
      "presence",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "projection",
      "sillage",
      "trail",
      "skin scent",
      "beast mode",
      "fragrance presence",
      "how far fragrance projects",
    ],
    educationTags: ["projection", "sillage", "technique", "fundamentals"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 80,
  },

  {
    slug: "fragrance-vocabulary",
    category: "Fragrance Fundamentals",
    difficulty: "beginner",
    topics: [
      "vocabulary",
      "descriptors",
      "fragrance language",
      "fresh",
      "warm",
      "woody",
      "animalic",
      "musky",
      "powdery",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "vocabulary",
      "fresh",
      "clean",
      "warm",
      "musky",
      "woody",
      "powdery",
      "animalic",
      "fragrance terms",
      "how to describe fragrance",
    ],
    educationTags: ["vocabulary", "fundamentals", "discovery", "descriptors"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 78,
  },

  {
    slug: "how-inspired-fragrances-work",
    category: "Fragrance Fundamentals",
    difficulty: "beginner",
    topics: [
      "inspired fragrances",
      "counterfeit",
      "perfumery process",
      "quality",
      "value",
      "brand education",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "inspired fragrance",
      "dupe",
      "counterfeit",
      "how inspired works",
      "original vs inspired",
      "fragrance dupe",
    ],
    educationTags: ["fundamentals", "inspired", "brand-education", "quality"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 72,
  },

  {
    slug: "why-fragrances-smell-different-on-everyone",
    category: "Scent Science",
    difficulty: "beginner",
    topics: [
      "body chemistry",
      "skin pH",
      "sebum",
      "microbiome",
      "body temperature",
      "skin testing",
      "olfaction",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "body chemistry",
      "skin pH",
      "why fragrance smells different",
      "skin chemistry",
      "fragrance on my skin",
      "why does fragrance smell different on me",
    ],
    educationTags: ["science", "body-chemistry", "skin", "testing"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 75,
  },

  {
    slug: "olfactory-fatigue",
    category: "Scent Science",
    difficulty: "beginner",
    topics: [
      "olfactory fatigue",
      "habituation",
      "nose reset",
      "over-application",
      "olfaction",
      "nose blind",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "olfactory fatigue",
      "nose blind",
      "can't smell my fragrance",
      "habituation",
      "why can't I smell my perfume",
      "nose adapt",
    ],
    educationTags: ["science", "olfaction", "application", "nose"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 68,
  },

  {
    slug: "the-science-of-longevity-and-projection",
    category: "Scent Science",
    difficulty: "intermediate",
    topics: [
      "longevity",
      "molecular weight",
      "volatility",
      "fixatives",
      "ambroxan",
      "base notes",
      "evaporation",
    ],
    families: [],
    notes: ["base"],
    occasions: [],
    collections: [],
    keywords: [
      "longevity",
      "how long fragrance lasts",
      "fixatives",
      "molecular weight",
      "ambroxan",
      "projection science",
      "why fragrance fades",
    ],
    educationTags: ["science", "longevity", "projection", "chemistry", "fixatives"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 62,
  },

  {
    slug: "how-to-sample-before-you-commit",
    category: "Wear & Application",
    difficulty: "beginner",
    topics: [
      "sampling",
      "testing",
      "strip testing",
      "skin testing",
      "5ml",
      "three-stage test",
      "dry-down",
    ],
    families: [],
    notes: [],
    occasions: [],
    collections: [],
    keywords: [
      "sampling",
      "how to test fragrance",
      "skin test",
      "5ml sample",
      "before buying fragrance",
      "testing fragrance",
    ],
    educationTags: ["sampling", "testing", "technique", "buying-guide"],
    seasonal: false,
    universalRelevance: true,
    relevanceScore: 73,
  },

  {
    slug: "the-world-of-floral-fragrances",
    category: "Fragrance Families",
    difficulty: "beginner",
    topics: [
      "floral fragrances",
      "floral families",
      "rose",
      "jasmine",
      "soliflore",
      "bouquet",
      "white floral",
      "peony",
    ],
    families: ["Floral", "White Floral", "Rose"],
    notes: ["heart"],
    occasions: [],
    collections: [],
    keywords: [
      "floral fragrance",
      "rose",
      "jasmine",
      "peony",
      "soliflore",
      "bouquet",
      "white floral",
      "tuberose",
      "gardenia",
      "floral family",
    ],
    educationTags: ["families", "floral", "discovery", "beginner"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 72,
  },

  {
    slug: "oriental-and-amber-fragrances",
    category: "Fragrance Families",
    difficulty: "intermediate",
    topics: [
      "oriental fragrance",
      "amber accord",
      "warm fragrance",
      "resins",
      "spice",
      "labdanum",
      "benzoin",
      "soft oriental",
    ],
    families: ["Amber", "Spicy", "Vanilla"],
    notes: ["base"],
    occasions: ["evening", "date night"],
    collections: [],
    keywords: [
      "oriental fragrance",
      "amber",
      "warm fragrance",
      "spice",
      "resins",
      "labdanum",
      "benzoin",
      "soft oriental",
      "floral oriental",
      "gourmand oriental",
    ],
    educationTags: ["families", "oriental", "amber", "warmth", "evening"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 68,
  },

  {
    slug: "woody-fragrances-explained",
    category: "Fragrance Families",
    difficulty: "intermediate",
    topics: [
      "woody fragrance",
      "sandalwood",
      "cedarwood",
      "vetiver",
      "oud",
      "patchouli",
      "fresh woody",
    ],
    families: ["Woody", "Oud"],
    notes: ["base"],
    occasions: [],
    collections: [],
    keywords: [
      "woody fragrance",
      "sandalwood",
      "cedarwood",
      "vetiver",
      "oud",
      "patchouli",
      "agarwood",
      "fresh woody",
      "woody family",
    ],
    educationTags: ["families", "woody", "oud", "sandalwood", "cedarwood"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 67,
  },

  {
    slug: "fresh-citrus-and-aquatic-fragrances",
    category: "Fragrance Families",
    difficulty: "beginner",
    topics: [
      "fresh fragrance",
      "citrus fragrance",
      "aquatic fragrance",
      "bergamot",
      "marine accord",
      "aromatic fresh",
      "longevity citrus",
    ],
    families: ["Fresh", "Citrus", "Aquatic"],
    notes: ["top"],
    occasions: ["casual", "summer", "daily wear"],
    collections: [],
    keywords: [
      "fresh fragrance",
      "citrus",
      "aquatic",
      "marine",
      "bergamot",
      "grapefruit",
      "lemon",
      "clean fragrance",
      "summer fragrance",
    ],
    educationTags: ["families", "fresh", "citrus", "aquatic", "summer"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 70,
  },

  {
    slug: "gourmand-fragrances-guide",
    category: "Fragrance Families",
    difficulty: "beginner",
    topics: [
      "gourmand fragrance",
      "vanilla",
      "coffee fragrance",
      "chocolate fragrance",
      "tonka bean",
      "coumarin",
      "edible fragrance",
    ],
    families: ["Gourmand", "Sweet"],
    notes: ["base", "heart"],
    occasions: [],
    collections: [],
    keywords: [
      "gourmand",
      "vanilla",
      "coffee",
      "chocolate",
      "caramel",
      "tonka",
      "sweet fragrance",
      "edible fragrance",
      "dessert fragrance",
    ],
    educationTags: ["families", "gourmand", "sweet", "vanilla", "edible"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 65,
  },

  {
    slug: "vanilla-and-amber-the-warm-base",
    category: "The Note Pyramid",
    difficulty: "beginner",
    topics: [
      "vanilla base note",
      "amber accord",
      "tonka bean",
      "labdanum",
      "benzoin",
      "vanillin",
      "base notes",
      "warm base",
    ],
    families: ["Vanilla", "Amber", "Gourmand"],
    notes: ["base"],
    occasions: [],
    collections: [],
    keywords: [
      "vanilla",
      "amber",
      "tonka",
      "vanillin",
      "labdanum",
      "benzoin",
      "base note",
      "warm base",
      "dry-down",
    ],
    educationTags: ["note-pyramid", "base-notes", "vanilla", "amber", "warmth"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 63,
  },

  {
    slug: "musks-the-hidden-foundation",
    category: "The Note Pyramid",
    difficulty: "intermediate",
    topics: [
      "musk",
      "synthetic musk",
      "fixative",
      "olfactory fatigue",
      "clean musk",
      "animalic",
      "Galaxolide",
      "ambroxan",
    ],
    families: [],
    notes: ["base"],
    occasions: [],
    collections: [],
    keywords: [
      "musk",
      "musks",
      "synthetic musk",
      "Galaxolide",
      "clean musk",
      "animalic musk",
      "fixative",
      "anosmia",
      "base note",
    ],
    educationTags: ["note-pyramid", "base-notes", "musk", "science", "fixative"],
    seasonal: false,
    universalRelevance: false,
    relevanceScore: 60,
  },
];
