import { defineConfig, devices } from "@playwright/test";

/**
 * Less-sweet fallback fix — browser rendering verification.
 *
 * Intercepts POST /api/concierge with a deterministic no-match fixture
 * (generated by gen-less-sweet-fixtures.ts). Verifies that:
 *   - The concierge panel renders the explanation text in the chat bubble
 *   - Zero product card links appear (fragrances=[])
 *
 * Run from repo root:
 *   npx playwright test --config scripts/pw-verify/playwright.less-sweet.config.ts
 *
 * Prerequisite: run gen-less-sweet-fixtures.ts once to generate the fixture file.
 */

const TEST_PORT = 3104;

export default defineConfig({
  testDir:   "./specs",
  testMatch: "**/concierge-less-sweet.spec.js",
  timeout:   90_000,
  retries:   0,
  workers:   1,
  reporter:  [["list"], ["json", { outputFile: "results/concierge-less-sweet/pw-report.json" }]],
  outputDir: "results/concierge-less-sweet/traces",

  use: {
    baseURL:    `http://localhost:${TEST_PORT}`,
    headless:   true,
    screenshot: "only-on-failure",
    trace:      "on-first-retry",
  },

  webServer: {
    command:             "npm run dev",
    url:                 `http://localhost:${TEST_PORT}`,
    reuseExistingServer: false,
    timeout:             120_000,
    env: {
      PORT:                          `${TEST_PORT}`,
      ANTHROPIC_API_KEY:             "sk-test-less-sweet-verification",
      ORDER_RECEIPT_SECRET:          "less-sweet-test-secret",
      NEXT_PUBLIC_SUPABASE_URL:      "http://localhost:54321",
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRFA0NiK7urfjjMvpL4luh9x2181Za7ua-ij-QfpuGg",
      SUPABASE_SERVICE_ROLE_KEY:     "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hj04zWl196z2-SBcc",
    },
  },

  projects: [
    {
      name: "concierge-desktop",
      use:  { ...devices["Desktop Chrome"], viewport: { width: 1280, height: 800 } },
    },
  ],
});
