import { defineConfig, devices } from "@playwright/test";

/**
 * Concierge response-text rendering verification.
 *
 * Intercepts POST /api/concierge with deterministic responses generated by
 * the patched planResponse + formatResponse pipeline (no LLM call). Verifies
 * that the real Next.js Concierge UI renders readable product names and article
 * titles in the message bubble — not internal markers or orphaned asterisks.
 *
 * This is mocked rendering verification, NOT a live-model quality test.
 *
 * Run from repo root:
 *   npx playwright test --config scripts/pw-verify/playwright.concierge-render.config.ts
 */

const TEST_PORT = 3103;

export default defineConfig({
  testDir:   "./specs",
  testMatch: "**/concierge-render.spec.js",
  timeout:   90_000,
  retries:   0,
  workers:   1,
  reporter:  [["list"], ["json", { outputFile: "results/concierge-render/pw-report.json" }]],
  outputDir: "results/concierge-render/traces",

  use: {
    baseURL:    `http://localhost:${TEST_PORT}`,
    headless:   true,
    screenshot: "only-on-failure",
    trace:      "on-first-retry",
  },

  webServer: {
    command:             "npm run dev",
    url:                 `http://localhost:${TEST_PORT}`,
    reuseExistingServer: false,
    timeout:             120_000,
    env: {
      PORT:                          `${TEST_PORT}`,
      // Replaced — Anthropic is never contacted; API route is fully intercepted.
      ANTHROPIC_API_KEY:             "sk-test-concierge-render-verification",
      ORDER_RECEIPT_SECRET:          "concierge-render-test-secret",
      NEXT_PUBLIC_SUPABASE_URL:      "http://localhost:54321",
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRFA0NiK7urfjjMvpL4luh9x2181Za7ua-ij-QfpuGg",
      SUPABASE_SERVICE_ROLE_KEY:     "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hj04zWl196z2-SBcc",
    },
  },

  projects: [
    {
      name: "concierge-desktop",
      use:  { ...devices["Desktop Chrome"], viewport: { width: 1280, height: 800 } },
    },
  ],
});
